apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-claim
  labels:
    app: nexus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  containers:
  - image: 'sonatype/nexus3:latest'
    name: nexus
    resources:
      limits:
        cpu: "4"
      requests: 
        cpu: "2"    
    ports:
    - containerPort: 8081
      name: nx-port-81
    volumeMounts:
    - name: nexus-data
      mountPath: /var/opt/jfrog/nexus/data
    - name: offliner-data
      mountPath: /tmp/offliner    
  volumes:
  - name: nexus-data
    persistentVolumeClaim:
     claimName: nexus-claim
  - name: offliner-data
    persistentVolumeClaim:
      claimName: maven-offliner      

---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  ports:
    - name: nx-port-81
      protocol: TCP
      port: 8080
      targetPort: 8081
  selector:
    app: nexus
  type: ClusterIP
  sessionAffinity: None

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nexus
spec:
  path: /
  to:
    kind: Service
    name: nexus
    weight: 100
  port:
    targetPort: nx-port-81