apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pam-postgres
  labels:
    app: postgres
spec:
  containers:
  - image: 'quay.io/pam_images/pam_postgres_bytea:11'
    name: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: supersecret
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    ports:
    - containerPort: 5432    
      name: postgres-port
    volumeMounts:
    - name: postgresql-data
      mountPath: /var/lib/postgresql/data
      readOnly: false
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
      claimName: postgresql-claim

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
  sessionAffinity: None